### ISSUE TITLE
Kanban Board set-up

### ISSUE THREAD

**Issue by helio3197** [helio3197/catalog-of-my-things#34]
### Kanban Board Ruby capstone project
[Our Kanban Board](https://github.com/helio3197/catalog-of-my-things/projects/1)

**We are 3 team members :**
- @estebanmual `Team Member #1`
- @ryxtor `Team Member  #2`
- @helio3197 `Team Member #3`

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi team,  

Your project is complete! Great job for nailing it right on the first attempt 🥇



![giphy](https://user-images.githubusercontent.com/77038610/154916093-53a75ff8-ba21-44ad-a25e-bdea6200d8f1.gif)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
